baseURL = 'https://master.haydenk.pages.dev/'
languageCode = 'en-us'
title = 'Hayden King'
theme = ['hugo-plain']
disableHugoGeneratorInject = true
ignoreErrors = [ "error-disable-taxonomy" ]
enableEmoji = true
canonifyURLs = true
enableRobotsTXT = true
mainSections = ['posts', 'bible-notes']

[module]
  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/icons/themify-icons"

[params]
  keywords = ['hayden', 'king', 'blog', 'software', 'development', 'aws']
  [[params.plugins.css]]
    link = "plugins/themify-icons/icons.css"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 13

  [[menus.main]]
    name = "Snippets"
    pageRef = "/snippets"
    weight = 12

  [[menus.main]]
    name = "Archive"
    pageRef = "/archive"
    weight = 99

  [[menus.footer]]
    name = 'Github'
    url = 'https://github.com/haydenk/'
    weight = 1
    [menus.footer.params]
      icon = 'fa-brands fa-github'

  [[menus.footer]]
    name = 'LinkedIn'
    url = 'http://linkedin.com/in/haydenking'
    weight = 2
    [menus.footer.params]
      icon = 'fa-brands fa-square-linkedin'

  [[menus.footer]]
    name = 'X'
    url = 'http://x.com/__haydenk'
    weight = 3
    [menus.footer.params]
      icon = 'fa-brands fa-square-x-twitter'

  [[menus.footer]]
    name = 'Instagram'
    url = 'http://instagram.com/mr.haydenk'
    weight = 4
    [menus.footer.params]
      icon = 'fa-brands fa-instagram'

  [[menus.footer]]
    name = 'RSS Feed'
    url = '/feed.xml'
    weight = 5
    [menus.footer.params]
      icon = 'fa-solid fa-rss'

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:day/:slug/'
    bible-notes = '/bible-notes/:year/:month/:day/:slug'
    snippets = '/snippets/:year/:month/:day/:slug/'
  [permalinks.section]
    posts = '/posts/'
    bible-notes = '/bible-notes/'
    snippets = '/snippets/'

[taxonomies]
    tag = "tags"
    category = "archive"

[outputFormats]
  [outputFormats.rss]
    mediaType = "application/rss+xml"
    baseName = "feed"
  [outputFormats.json]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true

[outputs]
  home = ['html','json','rss']
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[pagination]
  pagerSize = 10

ignoreLogs = ['warning-goldmark-raw-html']
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = false