baseURL = 'https://haydenk.github.io/blog/'
languageCode = 'en-us'
title = 'Hayden King'
theme = 'github.com/athul/archie'
disableHugoGeneratorInject = true
disableKinds = [ "taxonomy" ]
ignoreErrors = [ "error-disable-taxonomy" ]
mainSections = ['posts']

[module]
  [[module.imports]]
    path = "github.com/athul/archie"
[params]
  description = "Hayden King Personal Blog"
  keywords = ['hayden', 'king', 'blog', 'software', 'development', 'aws']

  mainCss = '/css/main.css'
  mainJs = '/js/main.js'
  [[params.baseStyles]]
    src = 'css/variables.css'
  [[params.baseStyles]]
    src = 'css/main.css'
  [[params.baseStyles]]
    src = 'css/syntax.css'

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = "Today"
  pageRef = "/today"
  weight = 12

[[menus.main]]
  name = "Snippets"
  pageRef = "/snippet"
  weight = 14

[[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 20

[[menus.main]]
  name = 'Github'
  url = 'https://github.com/haydenk/'
  weight = 98
  [menus.main.params]
    target = '_blank'
    rel = 'external'

[[menus.main]]
  name = 'LinkedIn'
  url = 'http://linkedin.com/in/haydenking'
  weight = 99
  [menus.main.params]
    target = '_blank'
    rel = 'external'

[permalinks]
  [permalinks.page]
    posts = '/post/:year/:month/:day/:slug/'
    today = '/today/:year-:month-:day/'
    snippet = '/snippet/:year/:month/:day/:slug/'
  [permalinks.section]
    posts = '/post/'
    today = '/today/'
    snippet = '/snippet/'

[outputFormats]
  [outputFormats.rss]
    mediaType = "application/rss+xml"
    baseName = "feed"
  [outputFormats.json]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true

[outputs]
  home = ['html','json','rss']
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
